//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERA.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> RewardPoints { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Role Role { get; set; }
    }
}
