INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (0, N'All', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (1, N'Developer', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (2, N'Sr. Developer', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (3, N'QA', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (4, N'BA', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (5, N'Product Manager', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (6, N'Architect', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (7, N'Director', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (8, N'Team Lead', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (9, N'CIO', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (10, N'CFO', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (11, N'COO', 1)
INSERT INTO [dbo].[Role] ([RoleID], [RoleDescription], [IsActive]) VALUES (12, N'CEO', 1)
