INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (0, N'All', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (1, N'Bentonville', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (2, N'Rogers', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (3, N'Springdale', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (4, N'Little Rock', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (5, N'Alma', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (6, N'Farmington', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (7, N'Little Flock', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (8, N'Fort Smith', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (9, N'Fayetteville', 1)
INSERT INTO [dbo].[Location] ([LocationID], [LocationDescription], [IsActive]) VALUES (10, N'Bellavista', 1)
